from enum import Enum


class SendEmail(Enum):
    FROM = "FROM"
    TO = "TO"
    REPLY_TO = "REPLY_TO"
    ATTACHMENT_DETAILS = "ATTACHMENT_DETAILS"
    S3_REGION_NAME = "S3_REGION_NAME"
    SES_REGION_NAME = "SES_REGION_NAME"
    TYPE = "TYPE"
    S3_BUCKET = "BUCKET"
    S3_PATH = "PATH"
    CONTEXT = "CONTEXT"
    TEMPLATE_NAME = "TEMPLATE_NAME"
    MESSAGE_TEMPLATE = "MESSAGE_TEMPLATE"
    SUBJECT = "SUBJECT"
