"""baseline

Revision ID: 2be7cb5e24ac
Revises: 
Create Date: 2022-04-08 09:12:31.381644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2be7cb5e24ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_message',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone_no', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('message_type', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_message')
    # ### end Alembic commands ###
