def prepare_notification_email_message(data):
    message_type = data.get("message_type")
    name = data.get("name")
    address = data.get("address")
    phone_no = data.get("phone_no")
    email = data.get("email")
    subject = data.get("subject")
    message = data.get("message")
    priority = data.get("priority")
    attachment_urls = data.get("attachment_urls")
    details = data.get("details", {})

    # Subject fallback
    if not subject:
        subject = f"{message_type} message from User"

    # --- Build user details only from filled fields ---
    # Common user fields
    user_fields = {
        "Name": name,
        "Address": address,
        "M(b)": phone_no,
        "Email": email,
        "Request Type": message_type,
        "Priority": priority
    }

    # Assembling a block from only non-empty values
    user_details_html = "<br/>".join(
        f"{label}: {value}"
        for label, value in user_fields.items()
        if value
    )

    # Details (dictionary of arbitrary fields)
    if details:
        details_html = "<br/>".join(
            prepare_details_record(key, value)
            for key, value in details.items()
            if value not in (None, "", [], {})
        )
    else:
        details_html = ""

    # Final HTML
    html_message = f"""
        <div>
            <p>{message}</p>
            {user_details_html}<br/>
            {details_html}
            <br/><br/>
            <p><em>****Autogenerated email from SingularityNet Team.**** </em></p>
        </div>
    """

    return {
        "attachment_urls": attachment_urls,
        "subject": subject,
        "message": html_message
    }


def prepare_details_record(key, value):
    key = key.capitalize()
    return f"{key}: {value}"
